apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-backend
  template:
    metadata:
      labels:
        app: gs-backend
    spec:
      containers:
      - name: gs-spring-boot-docker
        image: acrgdvivo.azurecr.io/gs-backend:latest
